[[collection]]
type = "card"
icon = "/img/e6data.svg"
title = "Performance and Research Engineer @ e6data"
date = "Jan 2025 - Present"
content = "Working in the core query engine team. Making algorithmic improvements for better memory efficiency and CPU utilization to enable faster SQL query execution."

[[collection]]
type = "card"
icon = "/img/saidl.png"
title = "Vice President @ Society for AI and Deep Learning"
date = "Aug 2024 - Jul 2025"
content = "Organized a [symposium](https://sites.google.com/goa.bits-pilani.ac.in/ai-symposium-2024/home), conducted courses, undertook research projects, hosted paper-reading sessions and hackathons."

[[collection]]
type = "card"
icon = "/img/tud.jpeg"
title = "Summer Intern @ Technische Universit√§t Dresden"
date = "May 2024 - Feb 2025"
content = "State-space models for neuromorphic event streams and point-cloud data. Work accepted at [NeVI @ ICCV'25](https://arxiv.org/abs/2411.12603)."

[[collection]]
type = "card"
icon = "/img/senselab.png"
title = "Undergraduate Research Assistant @ SenseLab"
date = "Aug 2024 - Dec 2024"
content = "Detecting user habits using CSI measurements from WiFi devices. Runner-up for best paper in WiP track at PERCOM'25."

[[collection]]
type = "card"
icon = "/img/dashlab.png"
title = "Undergraduate Researcher @ DaSH Lab"
date = "Apr 2023 - Dec 2024"
content = "Designing a cluster-aware file-level adaptive striping framework for parallel file-systems (BeeGFS). Published at [IEEE CLUSTER'23](https://ieeexplore.ieee.org/abstract/document/10321840/)."

[[collection]]
type = "card"
icon = "/img/kratos.png"
title = "Core Member, Software Team @ Project Kratos"
date = "Jun 2022 - Apr 2024"
content = "Implemented a visual servoing algorithm using a custom-trained YOLO as the object detector, integrated PID-based GPS navigation with the rover's tech stack. 2nd Place in Autonomous Task at IRC'24. [Project website](https://kratos-the-rover.github.io/)."

[[collection]]
type = "card"
icon = "/img/appcair.png"
title = "Undergraduate Researcher @ APPCAIR"
date = "May 2023 - Dec 2023"
content = "Explored causal neural network pruning strategies that preserve feature importances, compared against L0, L1, Rank-based and Learning-Compression Algorithms. [Code](https://github.com/yashrb24/granger-causality-pruning)."

[[collection]]
type = "card"
icon = "/img/isro.png"
title = "Summer Intern @ NESAC"
date = "May 2023 - Aug 2023"
content = "Used UNets and LSTMs for rainfall prediction using satellite data. Experimented with genetic algorithms to compare model performance against gradient-descent based optimisers. Work accepted as a poster at IGARSS'24."
