[[update]]
date = "2025-12-15"
text = "The preprint and codebase of [our ICLR Submission](https://arxiv.org/pdf/2511.01554) is out!"

[[update]]
date = "2025-09-19"
text = "Check out [this blog post](https://www.e6data.com/blog/german-strings-faster-analytics) about some of the work I did at e6data"

[[update]]
date = "2025-07-13"
text = "The [work](https://arxiv.org/pdf/2411.12603) of my DAAD-WISE Internship got accepted at NeVI workshop @ ICCV!"

[[update]]
date = "2025-06-24"
text = "Selected to attend Microsoft Research India's Academic Summit!"

[[update]]
date = "2025-06-19"
text = "Graduated from BITS with an Honours and Distinction!"

[[update]]
date = "2025-01-26"
text = "Attending Google Deepmind's Research Symposium at their Bangalore office"

[[update]]
date = "2025-01-20"
text = "Started a new role as Performance and Research Engineer at [e6data](https://www.e6data.com)"
